import Mathlib
import Challenge.MIPStarRE.LDT.Basic.ParametersBase
import Challenge.MIPStarRE.QPBT.Algebra.Coefficients
import Challenge.MIPStarRE.QPBT.Algebra.Subspaces
import Challenge.MIPStarRE.Quantum.FiniteMatrix.Basic
import Challenge.MIPStarRE.QPBT.Algebra.FieldBasis
import Challenge.MIPStarRE.QPBT.Algebra.Lines
import Challenge.MIPStarRE.QPBT.Algebra.LowDegreeCode
import Challenge.MIPStarRE.QPBT.State
import Challenge.MIPStarRE.QPBT.Algebra.Pauli
import Challenge.MIPStarRE.QPBT.Algebra.SelfDualBasis
import Challenge.MIPStarRE.Quantum.Measurement
import Challenge.MIPStarRE.QPBT.Algebra.SelfDualBasisTheorems
import Challenge.MIPStarRE.LDT.Basic.Distribution
import Challenge.MIPStarRE.QPBT.Algebra.PauliTheorems
import Challenge.MIPStarRE.QPBT.Games.Defs
import Challenge.MIPStarRE.QPBT.Test.LowDegreeGame
import Challenge.MIPStarRE.QPBT.Test.MagicSquare
import Challenge.MIPStarRE.QPBT.Test.PauliBasisTest
import Challenge.MIPStarRE.QPBT.Test.SoundnessDefs
import Challenge.MIPStarRE.QPBT.Test.QubitForm

/-!
# Challenge: quantum soundness of the Pauli basis test

Self-contained comparator challenge for `MIPStarRE.QPBT.pauli_soundness` and
`MIPStarRE.QPBT.pauli_soundness_qubit`, the source statements of `thm:pauli`
and `cor:pauli-binary` — the quantum soundness of the Pauli basis test
(Natarajan, Wright, "NEEXP in MIP*", and the low-degree chapter of the
quantum low individual degree test literature), the ingredient that turns the
classical low-degree test into a Pauli-braiding-style rigidity statement.

The challenge is **Mathlib-only**: apart from Mathlib it imports nothing but
its own modules under `Challenge/`, one for each library module that
contributes to the closure.  Together they re-declare, verbatim and in
dependency order, every definition in the transitive closure of the statements
of the two theorems; the theorems themselves are stated here with `sorry`.
Those modules and their imports mirror the library's own module partition
and import graph.  That is not cosmetic: Lean caches a nested proof and
a `match` auxiliary *per module*, names it after the first declaration of that
module that needs it, and lets a declaration see only the instances its
module's imports bring into scope, while the comparator compares the full
`ConstantInfo` of every closure constant, values and proofs included.  A
single-file challenge therefore cannot reproduce those names whenever the
library needs the same fact in two modules; the mirrored partition reproduces
them by construction.

The set of challenge modules is the entire human audit surface: a reader who
agrees that they state the intended theorems does not need to read anything
else.  The
[comparator](https://github.com/leanprover/comparator) tool verifies
mechanically that the [MIPStarRE](https://github.com/LionSR/MIPStarRE)
library declares statements identical to these and proves the theorems using
no axioms beyond `propext`, `Quot.sound`, and `Classical.choice`.

Each declaration carries a provenance comment (`-- source: <file>:<lines>`)
pointing at its origin in the MIPStarRE library, where docstrings cite the
paper passages being encoded, and each challenge module names the library
module it mirrors.  These files are generated by
`scripts/comparator/` in that repository; see the README alongside this file
for how to run the verification.
-/

open scoped BigOperators MatrixOrder Matrix ComplexOrder
-- Compiler-generated declarations in the closure (no source
-- range); they regenerate identically during elaboration:
--   MIPStarRE.QPBT.pauliWinPredicate._sparseCasesOn_7  (from MIPStarRE/QPBT/Test/PauliBasisTest.lean)
--   MIPStarRE.QPBT.MsType.ctorIdx  (from MIPStarRE/QPBT/Test/MagicSquare.lean)
--   MIPStarRE.QPBT.msWinPredicate._sparseCasesOn_1  (from MIPStarRE/QPBT/Test/MagicSquare.lean)
--   MIPStarRE.QPBT.isCompl_registerSubmodule_canonicalComplement._simp_1_4  (from MIPStarRE/QPBT/Algebra/Subspaces.lean)
--   MIPStarRE.QPBT.isCompl_registerSubmodule_canonicalComplement._simp_1_6  (from MIPStarRE/QPBT/Algebra/Subspaces.lean)
--   MIPStarRE.QPBT.isCompl_registerSubmodule_canonicalComplement._simp_1_3  (from MIPStarRE/QPBT/Algebra/Subspaces.lean)
--   MIPStarRE.QPBT.pauliWinPredicate._sparseCasesOn_2  (from MIPStarRE/QPBT/Test/PauliBasisTest.lean)
--   MIPStarRE.QPBT.validPauliAnswer._sparseCasesOn_3  (from MIPStarRE/QPBT/Test/PauliBasisTest.lean)
--   MIPStarRE.QPBT.PauliType.ctorElimType  (from MIPStarRE/QPBT/Test/PauliBasisTest.lean)
--   MIPStarRE.QPBT.PauliAnswer.ctorIdx  (from MIPStarRE/QPBT/Test/PauliBasisTest.lean)
--   MIPStarRE.QPBT.prefixRank.eq_1  (from MIPStarRE/QPBT/Algebra/Subspaces.lean)
--   MIPStarRE.QPBT.pauliWinPredicate._sparseCasesOn_1  (from MIPStarRE/QPBT/Test/PauliBasisTest.lean)
--   MIPStarRE.QPBT.pauliAnswerOrZero._sparseCasesOn_1  (from MIPStarRE/QPBT/Test/PauliBasisTest.lean)
--   MIPStarRE.QPBT.PauliKind.ofNat_ctorIdx  (from MIPStarRE/QPBT/Algebra/Pauli.lean)
--   MIPStarRE.QPBT.PauliType.proxyTypeEquiv  (from MIPStarRE/QPBT/Test/PauliBasisTest.lean)
--   MIPStarRE.QPBT.isCompl_registerSubmodule_canonicalComplement._simp_1_5  (from MIPStarRE/QPBT/Algebra/Subspaces.lean)
--   MIPStarRE.QPBT.msWinPredicate._sparseCasesOn_2  (from MIPStarRE/QPBT/Test/MagicSquare.lean)
--   MIPStarRE.QPBT.exists_self_dual_normal_basis_gal._simp_1_2  (from MIPStarRE/QPBT/Algebra/FieldBasis.lean)
--   MIPStarRE.QPBT.instInhabitedMsType.default  (from MIPStarRE/QPBT/Test/MagicSquare.lean)
--   MIPStarRE.QPBT.validPauliAnswer._sparseCasesOn_5  (from MIPStarRE/QPBT/Test/PauliBasisTest.lean)
--   MIPStarRE.QPBT.trace_group_algebra_pairing._simp_1_2  (from MIPStarRE/QPBT/Algebra/FieldBasis.lean)
--   MIPStarRE.QPBT.PauliKind.ofNat  (from MIPStarRE/QPBT/Algebra/Pauli.lean)
--   MIPStarRE.QPBT.MsAnswer.ctorIdx  (from MIPStarRE/QPBT/Test/MagicSquare.lean)
--   MIPStarRE.QPBT.normal_basis_trace_dual_apply._simp_1_3  (from MIPStarRE/QPBT/Algebra/FieldBasis.lean)
--   MIPStarRE.LDT.Distribution.mk.congr_simp  (from MIPStarRE/LDT/Basic/Distribution.lean)
--   MIPStarRE.QPBT.PauliType.ctorIdx  (from MIPStarRE/QPBT/Test/PauliBasisTest.lean)
--   MIPStarRE.QPBT.PauliKind.enumList  (from MIPStarRE/QPBT/Algebra/Pauli.lean)
--   MIPStarRE.QPBT.PauliType.point.inj  (from MIPStarRE/QPBT/Test/PauliBasisTest.lean)
--   MIPStarRE.QPBT.validPauliAnswer._sparseCasesOn_2  (from MIPStarRE/QPBT/Test/PauliBasisTest.lean)
--   MIPStarRE.QPBT.PauliAnswer.ctorElimType  (from MIPStarRE/QPBT/Test/PauliBasisTest.lean)
--   MIPStarRE.QPBT.normal_basis_trace_dual_apply._simp_1_2  (from MIPStarRE/QPBT/Algebra/FieldBasis.lean)
--   MIPStarRE.QPBT.PauliType.point.injEq  (from MIPStarRE/QPBT/Test/PauliBasisTest.lean)
--   MIPStarRE.QPBT.PauliKind.enumList_nodup  (from MIPStarRE/QPBT/Algebra/Pauli.lean)
--   MIPStarRE.QPBT.registerSubmodule_eq_spanSubset._simp_1_2  (from MIPStarRE/QPBT/Algebra/Subspaces.lean)
--   MIPStarRE.QPBT.validPauliAnswer._sparseCasesOn_1  (from MIPStarRE/QPBT/Test/PauliBasisTest.lean)
--   MIPStarRE.QPBT.pauliWinPredicate._sparseCasesOn_3  (from MIPStarRE/QPBT/Test/PauliBasisTest.lean)
--   MIPStarRE.QPBT.pauliWinPredicate._sparseCasesOn_5  (from MIPStarRE/QPBT/Test/PauliBasisTest.lean)
--   MIPStarRE.QPBT.pauliWinPredicate._sparseCasesOn_8  (from MIPStarRE/QPBT/Test/PauliBasisTest.lean)
--   MIPStarRE.QPBT.validPauliAnswer._sparseCasesOn_4  (from MIPStarRE/QPBT/Test/PauliBasisTest.lean)
--   MIPStarRE.QPBT.MsType.proxyTypeEquiv  (from MIPStarRE/QPBT/Test/MagicSquare.lean)
--   MIPStarRE.QPBT.registerSubmodule.eq_1  (from MIPStarRE/QPBT/Algebra/Subspaces.lean)
--   MIPStarRE.QPBT.pauliWinPredicate._sparseCasesOn_4  (from MIPStarRE/QPBT/Test/PauliBasisTest.lean)
--   MIPStarRE.QPBT.instInhabitedPauliKind.default  (from MIPStarRE/QPBT/Algebra/Pauli.lean)
--   MIPStarRE.QPBT.canonicalComplement.eq_1  (from MIPStarRE/QPBT/Algebra/Subspaces.lean)
--   MIPStarRE.QPBT.PauliKind.enumList_getElem?_ctorIdx_eq  (from MIPStarRE/QPBT/Algebra/Pauli.lean)
--   MIPStarRE.QPBT.validPauliAnswer._sparseCasesOn_6  (from MIPStarRE/QPBT/Test/PauliBasisTest.lean)
--   MIPStarRE.QPBT.pauliWinPredicate._sparseCasesOn_6  (from MIPStarRE/QPBT/Test/PauliBasisTest.lean)
--   MIPStarRE.QPBT.PauliKind.ctorIdx  (from MIPStarRE/QPBT/Algebra/Pauli.lean)

namespace MIPStarRE.QPBT

open MIPStarRE.LDT MIPStarRE.Quantum

-- source: MIPStarRE/QPBT/Test/Soundness.lean:38-62  (MIPStarRE.QPBT.pauli_soundness)
/-- `thm:pauli`: every sufficiently successful Pauli basis test strategy admits
local isometries and an auxiliary unit state for which the state and both
operator families are close at scale `deltaQld`.  The theorem uses the
once-and-for-all self-dual-normal field model selected by `fixedFieldModel` for
each admissible size, rather than a freshly quantified field identification.
Blueprint
`thm:pauli`; paper origin
`references/qpbt-paper/08_classical_and_quantum_low_degree_tests.tex:1426-1447`.

The paper's asymptotic constants are encoded by the explicit `deltaQld`
functional; the squared operator distances use the quantitative convention of
blueprint `def:povm-distance`.
-/
theorem pauli_soundness :
    ∃ a b : ℝ, 1 ≤ a ∧ 0 < b ∧ b < 1 ∧
      ∀ (P : AdmissibleParams) (ε : ℝ), 0 ≤ ε →
        ∀ S : Strategy (pauliBasisTest P), 1 - ε ≤ S.value →
          ∃ w : PauliSoundnessWitness P S,
            ‖isometryTensor w.φA w.φB S.ψ - idealState P w.aux‖ ≤
                deltaQld a b ε P.m P.d P.q ∧
            (∀ W : PauliKind,
              pauliOperatorDistanceA P S w W ≤ deltaQld a b ε P.m P.d P.q) ∧
            (∀ W : PauliKind,
              pauliOperatorDistanceB P S w W ≤ deltaQld a b ε P.m P.d P.q) := by
  sorry

-- source: MIPStarRE/QPBT/Test/QubitForm.lean:411-436  (MIPStarRE.QPBT.pauli_soundness_qubit)
/-- `cor:pauli-binary`: soundness of the Pauli basis test in qubit
coordinates. Blueprint `cor:pauli-binary`, paper
`08_classical_and_quantum_low_degree_tests.tex:1450-1491`.

The theorem assumes a nonnegative error parameter, as in the source, and uses
only `P.model` and its stored basis dimension.

**Proof dependency:** The coordinate change and all three error identities are
proved, and the source theorem `pauli_soundness` is proved as well, so this
corollary is complete: its axiom closure is `propext`, `Classical.choice` and
`Quot.sound`. The composition that closed `pauli_soundness` is recorded in
issue #614, under the umbrella issue #529. -/
theorem pauli_soundness_qubit :
    ∃ a b : ℝ, 1 ≤ a ∧ 0 < b ∧ b < 1 ∧
      ∀ (P : AdmissibleParams) (ε : ℝ), 0 ≤ ε →
        ∀ S : Strategy (pauliBasisTest P), 1 - ε ≤ S.value →
          ∃ w : QubitSoundnessWitness P S,
            ‖isometryTensor w.φA w.φB S.ψ - idealQubitState P w.aux‖ ≤
                deltaQld a b ε P.m P.d P.q ∧
            (∀ W : PauliKind,
              qubitOperatorDistanceA P S w W ≤
                deltaQld a b ε P.m P.d P.q) ∧
            ∀ W : PauliKind,
              qubitOperatorDistanceB P S w W ≤
                deltaQld a b ε P.m P.d P.q := by
  sorry

end MIPStarRE.QPBT
