name = "QPBTComparator"
version = "0.1.0"
defaultTargets = ["QPBTComparator", "Challenge", "Solution"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
maxSynthPendingDepth = 3

[[require]]
name = "MIPStarRE"
git = "https://github.com/Dengnifer/MIPStarRE-QPBT.git"
rev = "8baaa22256aa5ff7946c82efc1fefcf95f97abbc"

[[lean_lib]]
name = "Challenge"
globs = ["Challenge"]

[[lean_lib]]
name = "Solution"

[[lean_lib]]
name = "QPBTComparator"
