name = "QPBTComparator"
version = "0.1.0"
defaultTargets = ["QPBTComparator", "Challenge", "Solution"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
maxSynthPendingDepth = 3

[[require]]
name = "MIPStarRE"
git = "https://github.com/Dengnifer/MIPStarRE-QPBT.git"
rev = "271e2d96a72c55b4b7432187afaa1f7d747aaa4e"

[[lean_lib]]
name = "Challenge"
globs = ["Challenge"]

[[lean_lib]]
name = "Solution"

[[lean_lib]]
name = "QPBTComparator"
